AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  law-and-cs-miniproject

  SAM Template for the law-and-cs-miniproject

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 29
    MemorySize: 128

Parameters:
  OpenAIKey:
    Type: String
    Description: OpenAI API Key

Resources:
  HighlighterFunction:
    Cors:
      AllowHeaders: "'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'" 
      AllowOrigin: "'*'"
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: highlighter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 29
      Events:
        Highlighter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /highlighter
            Method: post
        PreflightedHighlighter:
          Type: Api
          Properties:
            Path: /highlighter
            Method: options
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HighlighterApi:
    Description: "API Gateway endpoint URL for the highlighter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/highlighter/"
  HighlighterFunction:
    Description: "Highlighter Lambda Function ARN"
    Value: !GetAtt HighlighterFunction.Arn
  HighlighterFunctionIamRole:
    Description: "Implicit IAM Role created for the highlighter function"
    Value: !GetAtt HighlighterFunctionRole.Arn
